apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quote-pdf
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  source:
    path: .
    repoURL: "https://github.com/Swapnil20001/argoCD.git"
    targetRevision: HEAD
  
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
   

